{
 "title": "Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Project Overview",
   "type": "table",
   "description": "A list of projects with Python and Vedro versions.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    DISTINCT ON (project_id)\n    project_id,\n    first_value(substring(environment->>'python_version', '^\\S+')) OVER (\n        PARTITION BY project_id ORDER BY saved_at DESC\n        RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING\n    ) as python_version,\n    last_value(environment->>'vedro_version') OVER (\n        PARTITION BY project_id ORDER BY saved_at DESC\n        RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING\n    ) as vedro_version\nFROM sessions\nWHERE environment->>'vedro_version' IS NOT NULL\n    AND discovered IS NOT NULL\n    AND project_id != 'unknown'\n    AND saved_at BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY project_id ASC\n"
    }
   ]
  },
  {
   "title": "Vedro",
   "type": "table",
   "description": "A table showing the latest Vedro version available on PyPi.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 3600,
     "fields": [
      { "jsonPath": "$.version", "name": "Latest Version", "type": "string" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Scenario Count",
   "type": "table",
   "description": "A list of projects with the count of total scenarios.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT project_id, discovered\nFROM (\n    SELECT\n        DISTINCT ON (project_id)\n        project_id,\n        discovered\n    FROM sessions\n    WHERE discovered is not NULL\n        AND saved_at BETWEEN $__timeFrom() AND $__timeTo()\n        AND project_id != 'unknown'\n    ORDER BY project_id ASC, discovered DESC\n) as t\nORDER BY discovered DESC, project_id ASC\n"
    }
   ]
  },
  {
   "title": "Startup Time",
   "type": "table",
   "description": "A list of projects with the median and average time to the first significant line of the test.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "select\n    project_id,\n    PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY elapsed) AS median,\n    ROUND(AVG(elapsed), 2) as avg\nfrom (\n    SELECT\n        project_id,\n        EXTRACT(epoch FROM started_at) - EXTRACT(epoch FROM inited_at) as elapsed\n    FROM sessions\n    WHERE started_at is not NULL\n        AND project_id != 'unknown'\n        AND saved_at BETWEEN $__timeFrom() AND $__timeTo()\n) as t\nGROUP BY project_id\nORDER BY avg DESC, project_id ASC\n"
    }
   ]
  },
  {
   "title": "Plugin Usage",
   "type": "table",
   "description": "Displays the plugins used across different projects and the number of projects using each plugin.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT name, count(*) as projects\nFROM (\n    SELECT\n        s.project_id as project_id,\n        p.name as name\n    FROM sessions as s\n    JOIN plugins as p\n        ON p.session_id = s.id\n    WHERE p.enabled IS TRUE\n        AND saved_at BETWEEN $__timeFrom() AND $__timeTo()\n        AND s.project_id != 'unknown'\n    GROUP by s.project_id, p.name\n) as t\nGROUP by name\nORDER BY projects DESC, name ASC\n"
    }
   ]
  },
  {
   "title": "Plugin Adoption",
   "type": "table",
   "description": "A list of projects with all enabled plugins (including their versions).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \n    stp.project_id, \n    p.name, \n    p.version \nFROM (\n    SELECT\n        DISTINCT ON (project_id) \n        project_id, \n        FIRST_VALUE(id) OVER (PARTITION BY project_id ORDER BY saved_at DESC) AS session_id                 \n    FROM \n        sessions                 \n    WHERE \n        environment->>'vedro_version' IS NOT NULL              \n        AND project_id != 'unknown'                \n        AND discovered IS NOT NULL\n      \n) AS stp\nLEFT JOIN \n    plugins AS p\n    ON stp.session_id = p.session_id\nWHERE \n    p.enabled = TRUE\nORDER BY \n    stp.project_id, \n    p.name"
    }
   ]
  }
 ]
}